en/upgrades/all-versions.rst
This does not need to be merged until 6th Jan live date
=> [#156] Update All Versions page

en/upgrades/nonembedded-codelist-changelog.rst
Re: #185
Additionally - splits Org Agency specific changes to new changelog table
=> Updates non-embedded codelist changelog

en/upgrades/integer-upgrade-to-2-01/migrating.rst
Replaces dev.iatistandard with iatistandard throughout
All changes by hand, includes many links that were google based links
=> [#174] Removes all dev.iatistandard urls

en/how-to-publish/select-data-to-publish.rst
Please note I may have got the syntax wrong for the internal links.
Please review
I have also bulleted each section for better formatting.
=> [#80] Creates links to main pages in the website

en/upgrades/integer-upgrade-to-2-01/migrating.rst
=> Upadting migration document

en/upgrades/integer-upgrade-to-2-01/2-01-headlines.rst
Rephrased headline changes doc to state that 2.01 is no longer "proposed"
=> Headlines live

en/upgrades/integer-upgrade-to-2-01/migrating.rst
=> Updates activity-website description

en/how-to-publish/select-data-to-publish.rst
=> Updates Linked To DFID Minimum Reqts on Gov.uk

en/how-to-publish/select-publishing-tool.rst
=> Link To Aidstream Videos On YouTube

en/how-to-publish/select-publishing-tool.rst, en/upgrades/nonembedded-codelist-changelog.rst
=> Merge master into live

en/upgrades/nonembedded-codelist-changelog.rst
Changelog updates for IATI/IATI-Codelists-NonEmbedded#150
=> Update NE-Codelist Changelog, 2017-04-20

en/upgrades/nonembedded-codelist-changelog.rst
Additions to the `OrganisationRegistrationAgency` Codelist
=> Update NEC Changelog 2017-06-12

en/how-to-publish/select-publishing-tool.rst
My rst knowledge is non-existent if the formatting is wrong I can change it.
=> Remove csvtoiati refs

en/upgrades/nonembedded-codelist-changelog.rst
Update changelog to reflect changes to non-embedded OrganisationRegistration codelist requested here:
https://discuss.iatistandard.org/t/approved-proposed-addition-to-the-organisation-registration-agency-codelist-argentina/944
https://discuss.iatistandard.org/t/approved-proposed-addition-to-the-organisation-registration-agency-codelist-ethiopia/941
=> Modifications 20170724

en/upgrades.rst, en/upgrades/decimal-upgrade-to-1-02.rst, en/upgrades/decimal-upgrade-to-1-03.rst, en/upgrades/decimal-upgrade-to-1-04.rst, en/upgrades/decimal-upgrade-to-2-02.rst, en/upgrades/integer-upgrade-to-2-01.rst, en/upgrades/nonembedded-codelist-changelog.rst
Implements the changes to resolve dead links put forward by @hayfield
=> Update live from master

en/upgrades/nonembedded-codelist-changelog.rst
Added XI-IATI-ADVZ and XI-IATI-AIAS
=> Update non-embedded code list

en/upgrades.rst
=> Update upgrades.rst - fix typo

en/datastore/guidance/data-formats.rst, en/datastore/guidance/forming-queries.rst
Change internal links to external links as internal links not working as expected on standard site.
=> Change internal links to external links

en/how-to-publish/select-publishing-tool.rst
Added (e.g. in Excel format) to Spreadsheet2IATI at request of Data 4 Development
=> Request change to publishing tool narrative

en/how-to-publish/select-publishing-tool.rst
Added publishing tool: Matthat Projectconnect.
=> Matthat projectconnect

en/upgrades/nonembedded-codelist-changelog.rst
=> Add code XI-IATI-DGF to IATI Organisation Identifier codelist

en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Tweaks to the formatting of the 2.03 changelog, so as to improve clarity.
=> 2.03 changelog tweaks

en/datastore/reference/data-api.rst
Fixes IATI/IATI-Datastore#274.
=> Fix datastore docs re last-updated-datetime

en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Add links to various Codelists.
=> Format Codelists in 2.03 Changelog

en/datastore/reference/structure-of-data.rst, en/how-to-publish/select-publishing-tool.rst, en/implementation-schedule.rst, en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
=> Fix title underline length

en/upgrades/nonembedded-codelist-changelog.rst
=> Add missing IATI Organisation Identifier items to changelog

en/upgrades/nonembedded-codelist-changelog.rst
Re: https://github.com/org-id/register/issues/219 https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/235
=> Updates description for org-id-guide

en/upgrades/nonembedded-codelist-changelog.rst
Change as per: https://discuss.iatistandard.org/t/update-to-the-iso-country-codelist-sz-eswatini/1397 and https://discuss.iatistandard.org/t/updated-url-for-the-humanitarian-plan-codelist/1396/
=> Changelog update 20180719

en/upgrades/all-versions/previous-process.rst
Linked to: https://github.com/IATI/IATI-Guidance/issues/322
@PetyaKangalova please can you check wording and approve. Then leave the merging to the devs.
=> Create page for previous upgrade process

en/upgrades/all-versions.rst
Linked to: https://github.com/IATI/IATI-Guidance/issues/322
@PetyaKangalova please can you check wording and approve. Then leave the merging to the devs.
=> Add upgrade process information to all-versions

en/upgrades.rst
https://github.com/IATI/IATI-Guidance/issues/322
Devs - I've added the new sub-page to the toctree at the top. Please check whether that is correct or not.
@PetyaKangalova please can you check wording and approve. Then leave the merging to the devs.
=> Update current upgrade information

en/upgrades/nonembedded-codelist-changelog.rst
Links to PR: https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/278
And Discuss post: https://discuss.iatistandard.org/t/update-currency-codelist-to-show-ves-bolivar-soberano/1591
=> 6th Dec 2018 changes to currency codes - changelog

en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Addition requested by the community: https://discuss.iatistandard.org/t/final-proposal-of-2-03-content/1054/12
=> Adding in link to Final Tech Summary 2.03

en/upgrades/nonembedded-codelist-changelog.rst
Added new AidType and FinanceType-category rows
=> Update: Updates to other non-embedded codelists

en/activity-budgets.rst, en/activity-classifications.rst, en/activity-dates-status.rst, en/activity-geography.rst, en/activity-participants.rst, en/activity-thematic-focus.rst, en/budgets-overview.rst, en/conditions.rst, en/countries-regions.rst, en/country-budget-alignment.rst, en/crs-fss.rst, en/financial-transactions.rst, en/humanitarian.rst, en/organisation-budgets-spend.rst, en/related-data.rst, en/related-documents.rst, en/results.rst, en/sdg-guidance.rst, en/self-defined-vocabularies.rst, en/sub-national-locations-all.rst, en/sub-national-locations.rst
Petya, I've gone through the GitHub change logs to find the last updated dates for each file. These will then pull through to the wagtail site. Would be great if you could sense check and make sure none are missing.
=> Update last updated dates

en/covid-19.rst
Additions made based on consultation with the IATI community. See details here: https://github.com/IATI/IATI-Guidance/issues/353
=> Update Covid-19 guidance with DAC sector code
